version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: financial-tracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_tracker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - financial_tracker_network

networks:
  financial_tracker_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
